name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v2

      # Set up JDK 17 for the build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Build the APK
      - name: Build APK
        run: flutter build apk --debug

      # Upload the built APK to GitHub as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
